### ISSUE TITLE
Moving past soft limits

### ISSUE THREAD

**Issue by yusufm** [Labsmore/pyuscope#157] opened 2023-04-18 06:41 UTC
When we perform a move with a value that would cause the end point to be greater than set soft limits, it throws a warning, but also goes the specified distance.

If we specific a value to move that will end up moving outside the soft limit, that we limit the move to the limit and no more.

This is apparent in calls to `motion_thread.jog()` with a value that will jog to greater than the expected limits.

**Comment by JohnDMcMaster** [comment] 2023-04-18 06:42
duplicate of https://github.com/Labsmore/pyuscope/issues/79

**Closed by JohnDMcMaster** 2023-04-18 06:42 UTC
